#enemy_color: "red"
enemy_color: "blue"


#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----USB相机参数-----#####
image_width: 1280
image_height: 720
fov_h: 57.7 #87.7
fov_v: 56.7 
new_fov_h: 27 #67
new_fov_v: 40.9
usb_frame_rate: 120
usb_exposure: 500 #1-80000______250
usb_gamma: 160
usb_gain: 10 #0-96

#####-----工业相机参数-----#####
camera_name: "hikrobot"
exposure_ms: 10
gain: 16.9
vid_pid: "2bdf:0001"

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

#####-----cboard参数-----#####
com_port: "/dev/gimbal"
baudrate: 115200          # 必须与下位机一致！
data_bits: 8
stop_bits: 1
parity: "none"
flow_control: "none"
timeout_ms: 50             # 读串口最多等20ms

yaw_kp: 0.5
yaw_kd: 0.1
pitch_kp: 0.5
pitch_kd: 0.1

#####-----tracker参数-----#####
fire_thresh: 0.0035
max_yaw_acc: 50
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6, 0]
R_pitch: [1]

min_detect_count: 5
max_temp_lost_count: 25
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: -0.8 # degree -2.5
pitch_offset: -1  # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
left_yaw_offset: -1
right_yaw_offset: -0.6
decision_speed: 10 # rad/s
high_speed_delay_time: 0.026 # s
low_speed_delay_time: 0.010 # s

#####-----shooter参数-----#####
first_tolerance: 5 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 3 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#####-----decider参数-----#####
mode: 1

#####-----工业相机标定参数-----#####
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]


# 重投影误差: 0.0771px
camera_matrix: [3769.4790943911462, 0, 808.60045149524751, 0, 3772.3150009087076, 573.89490974770069, 0, 0, 1]
distort_coeffs: [-0.012264474128282118, 0.15364646922378458, 0.0023309588329834285, -0.0026824789944141143, 0]

# 相机同理想情况的偏角: yaw-1.22 pitch-1.41 roll2.68 degree
R_camera2gimbal: [0.020070973457829933, -0.025520261687840801, 0.9994727971625037, -0.99870269105742271, 0.046280826722064461, 0.021237230341650159, -0.046798407014738662, -0.99860242405138711, -0.024558252779391276]
t_camera2gimbal: [-0.60901342903212285, 0.17992195393974511, 0.363992671333289]


